// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.DLL.Context.ApplicationDbContext;

#nullable disable

namespace Server.DLL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126204814_CreateDiscipline")]
    partial class CreateDiscipline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameDiscipline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.Educator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicDegree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Educators");
                });

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.EducatorAdditionalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EducatorId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<byte>>("Image")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialtyOrFieldOfStudy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EducatorId")
                        .IsUnique();

                    b.ToTable("EducatorAdditionalInfos");
                });

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.EducatorDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("EducatorAdditionalInfoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("EducatorAdditionalInfoId");

                    b.ToTable("EducatorDisciplines");
                });

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.EducatorAdditionalInfo", b =>
                {
                    b.HasOne("Server.DLL.Models.Entities.Educator.Educator", null)
                        .WithOne("EducatorAdditionalInfo")
                        .HasForeignKey("Server.DLL.Models.Entities.Educator.EducatorAdditionalInfo", "EducatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.EducatorDiscipline", b =>
                {
                    b.HasOne("Server.DLL.Models.Entities.Educator.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DLL.Models.Entities.Educator.EducatorAdditionalInfo", null)
                        .WithMany("EducatorDisciplines")
                        .HasForeignKey("EducatorAdditionalInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.Educator", b =>
                {
                    b.Navigation("EducatorAdditionalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Server.DLL.Models.Entities.Educator.EducatorAdditionalInfo", b =>
                {
                    b.Navigation("EducatorDisciplines");
                });
#pragma warning restore 612, 618
        }
    }
}
